Return a code based on the outcome of tests
intra2net/avocado-i2n pull request #15
Opened 2021-06-24 21:18 UTC by samiraguiar

Return 1 when at least one of the tests failed, errored or was
interrupted.

2021-11-24 18:45 UTC, pevogam commented
@samiraguiar Could you rebase this PR or use the already rebased version from the commit https://github.com/intra2net/avocado-i2n/commit/daab2fe789b4ff4ec503a79672d66899843c413a to push again here?

2021-11-25 14:52 UTC, pevogam requested changes
Just left a few comments, mostly small things.

2021-11-25 14:52 UTC, pevogam commented on avocado_i2n/plugins/manu.py
> +                if setup_func(config, "0m%s" % i) not in [None, 0]:
Any idea under what conditions can we have have `None` here?

2021-11-25 14:52 UTC, pevogam commented on avocado_i2n/runner.py
> +        Whether all tests run under this runner passed.
Can we use a complete sentence here like "Evaluate if all tests run under this runner have an ok status." and use `all_tests_ok`, `all_tests_good` or something other than "passed" which could be confused with PASS status?

2021-11-25 14:52 UTC, pevogam commented on avocado_i2n/runner.py
> +        :returns: True if all tests passed else False
Then here the description style for the plugin is:
```
:returns: whether all tests ended with acceptable status
```
(i.e. starting with small-cap "whether")

2021-11-25 14:52 UTC, pevogam commented on avocado_i2n/runner.py
> +    def all_tests_passed(self):
As this sounds more like a general job property than a runner property I guess we could also use a job method like:
```python
    def get_failed_tests(self):
        """Gets the tests with status 'FAIL' and 'ERROR' after the Job ended.

        :return: List of failed tests
        """
        tests = []
        if self.result:
            for test in self.result.tests:
                if test.get('status') in ['FAIL', 'ERROR']:
                    tests.append(test)
        return tests
```
and check if the list is empty but this could be done later on and at the very least I am noting it here for myself. In short, the runner class is best focused on running the tests and not tracking test results which is already done by the job class.

2021-11-25 15:19 UTC, samiraguiar commented on avocado_i2n/plugins/manu.py
> +                if setup_func(config, "0m%s" % i) not in [None, 0]:
Not sure anymore, but I guess this was meant more as a guardian in case the function returns the default "None" value when no return statement is present

2021-11-25 15:21 UTC, samiraguiar commented on avocado_i2n/runner.py
> +    def all_tests_passed(self):
That is definitely better as it delegates the notion of _failure_ to avocado instead of "leaking" internal concepts like test statuses. I had missed that method at the time.

2021-11-25 15:23 UTC, samiraguiar commented on avocado_i2n/runner.py
> +        :returns: True if all tests passed else False
ACK

2021-11-25 15:23 UTC, samiraguiar commented on avocado_i2n/runner.py
> +        Whether all tests run under this runner passed.
ACK

2021-11-25 15:24 UTC, pevogam commented on avocado_i2n/plugins/manu.py
> +                if setup_func(config, "0m%s" % i) not in [None, 0]:
This is what I would have guessed too, perhaps a good idea then is to leave a small TODO here that we can drop this consideration of None in the future.

2021-11-25 15:24 UTC, pevogam commented on avocado_i2n/runner.py
> +    def all_tests_passed(self):
It might be something new, I haven't looked at it before.

2021-11-25 16:28 UTC, pevogam commented on avocado_i2n/runner.py
> +    def all_tests_passed(self):
I will leave this conversation unresolved for future reference.

2021-11-25 16:35 UTC, pevogam approved these changes
LGTM

2021-11-25 16:35 UTC, merged