Add type hint annotations for the remaining modules and subpackages
intra2net/avocado-i2n pull request #32
Opened 2024-09-09 13:02 UTC by laracroft37

Include a minimal mypy config file and CI workflow too.

2024-09-12 11:01 UTC, pevogam requested changes
Great steps forward, I left any remaining requested changes as comments.

2024-09-12 12:04 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +Data  structure containing tests as nodes in a bidirected graph with edges to their
Done

2024-09-12 12:21 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
Done

2024-09-12 12:23 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +    def new_workers(self, workers: dict[list[TestWorker], TestWorker]) -> None:
Done

2024-09-12 12:24 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +        The number and percentage of tests that are fully finished will not be run again.
Done

2024-09-12 12:26 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +        def get_display_id(node: list["TestNode"]) -> str:
Done

2024-09-12 12:28 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +    ) -> list[TestObject] | Any:
Done

2024-09-12 12:29 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +    ) -> list[ImageObject]:
Done

2024-09-12 12:30 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +    ) -> tuple[list[TestObject], Any]:
Done

2024-09-12 12:31 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +        def needed_vms() -> tuple[list[TestObject], Any] | Any:
Done

2024-09-12 12:33 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +        Use the nodes restriction string and possibly restricting to a single test object
Done

2024-09-12 12:33 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +    ) -> tuple[list[TestNode], list[TestNode]]:
Done

2024-09-12 12:34 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +    ) -> list[TestNode] | TestNode:
Done

2024-09-12 12:36 UTC, laracroft37 commented on avocado_i2n/cartgraph/object.py
> -
are the two line after the INTERFACE or before??

2024-09-12 13:51 UTC, laracroft37 commented on avocado_i2n/cartgraph/object.py
> +    def component_form(self) -> Params:
Done

2024-09-12 13:52 UTC, laracroft37 commented on avocado_i2n/cartgraph/object.py
> +        If the test object is permanent, it can only be created manually.
Done

2024-09-12 13:53 UTC, laracroft37 commented on avocado_i2n/cartgraph/worker.py
> +    def __init__(self, id: str, workers: str = None) -> None:
Done

2024-09-12 13:54 UTC, laracroft37 commented on avocado_i2n/cmd_parser.py
> +Need to write something here.
Done

2024-09-12 13:56 UTC, laracroft37 commented on avocado_i2n/cmd_parser.py
>      """
noted for both

2024-09-12 13:57 UTC, laracroft37 commented on avocado_i2n/cmd_parser.py
> -    Add env processing hooks to handle on/off state get/set operations
Done

2024-09-12 13:59 UTC, laracroft37 commented on avocado_i2n/plugins/auto.py
> +Autotesting.
Done

2024-09-12 14:00 UTC, laracroft37 commented on avocado_i2n/plugins/auto.py
> +    """Autotesting......"""
Done

2024-09-12 14:01 UTC, laracroft37 commented on avocado_i2n/plugins/auto.py
> +    def configure(self, parser: QAArgumentParser) -> None:
Done

2024-09-12 14:03 UTC, laracroft37 commented on avocado_i2n/plugins/auto.py
> -        Take care of command line overwriting, parameter preparation,
Done for the 3

2024-09-12 14:04 UTC, laracroft37 commented on avocado_i2n/plugins/auto.py
> +            config: Params, name: str = None, job_config: str = None
Done

2024-09-12 14:05 UTC, laracroft37 commented on avocado_i2n/plugins/manu.py
> +Manual settings for the test run.
Done

2024-09-12 14:06 UTC, laracroft37 commented on avocado_i2n/plugins/manu.py
> +    """Manually setup test run."""
Done

2024-09-12 14:10 UTC, laracroft37 commented on avocado_i2n/plugins/manu.py
> -        Take care of command line overwriting, parameter preparation,
Done

2024-09-12 14:10 UTC, laracroft37 commented on avocado_i2n/plugins/settings.py
> +    """I2NSettings for setting the path."""
Done

2024-09-12 14:11 UTC, laracroft37 commented on avocado_i2n/plugins/settings.py
> +        """Adjust the settings of the path."""
Done

2024-09-12 14:13 UTC, laracroft37 commented on avocado_i2n/states/btrfs.py
> +    def show(cls, params: Params, object: list["TestObject"] = None) -> None:
Done

2024-09-12 14:19 UTC, laracroft37 commented on avocado_i2n/states/btrfs.py
> +    def get(cls, params: Params, object: list["TestObject"] = None) -> None:
Done

2024-09-12 14:20 UTC, laracroft37 commented on avocado_i2n/states/ramfile.py
> +    def set_root(cls, params: Params, object: list["TestObject"] = None) -> None:
Done

2024-09-12 14:20 UTC, laracroft37 commented on avocado_i2n/params_parser.py
> -    """Custom directory for all config files."""
Done

2024-09-12 14:23 UTC, laracroft37 commented on avocado_i2n/params_parser.py
>      """Overwrite config file for all tests (nodes)."""
Done

2024-09-12 14:23 UTC, laracroft37 commented on avocado_i2n/params_parser.py
>      """Overwrite config file for all vms (a category of objects)."""
Done

2024-09-12 14:24 UTC, laracroft37 commented on avocado_i2n/params_parser.py
>      """Overwrite config file for all objects."""
Done

2024-09-12 14:26 UTC, laracroft37 commented on avocado_i2n/params_parser.py
> -        Parsed content representation used in reports of parsing steps.
Done

2024-09-12 14:28 UTC, laracroft37 commented on avocado_i2n/params_parser.py
> +        Parse string representation used in reports of parsing steps.
Done

2024-09-12 14:30 UTC, laracroft37 commented on avocado_i2n/params_parser.py
>      :param variant_strs: variant restrictions for each object as key, value pair
Done

2024-09-12 14:31 UTC, laracroft37 commented on avocado_i2n/vmnet/interface.py
> +    def mac(self, value: Params = None) -> Params:
Done

2024-09-12 14:33 UTC, laracroft37 commented on avocado_i2n/vmnet/node.py
> +    def interfaces(self, value: VMInterface = None) -> VMInterface:
Done

2024-09-12 14:34 UTC, laracroft37 commented on avocado_i2n/vmnet/node.py
> +    def remote_sessions(self, value: RemoteSession = None) -> RemoteSession:
Done

2024-09-12 14:35 UTC, laracroft37 commented on avocado_i2n/vmnet/node.py
> +    def check_interface(self, condition: Callable[Any, Any]) -> VMInterface | None:
Done

2024-09-12 14:35 UTC, laracroft37 commented on avocado_i2n/vmnet/node.py
> +    def get_single_interface(self) -> list[VMInterface]:
Done

2024-09-12 14:36 UTC, laracroft37 commented on avocado_i2n/vmnet/node.py
> +    def get_session(self, serial: bool = False) -> VM:
Done

2024-09-12 14:37 UTC, laracroft37 commented on avocado_i2n/vmnet/tunnel.py
> +    def left_net(self, value: VMNetconfig = None) -> VMNetconfig | None:
Done

2024-09-12 14:38 UTC, laracroft37 commented on avocado_i2n/vmnet/tunnel.py
> +    def right_net(self, value: VMNetconfig = None) -> VMNetconfig | None:
Done

2024-09-12 14:38 UTC, laracroft37 commented on avocado_i2n/vmnet/tunnel.py
> +            return None
Done

2024-09-12 14:38 UTC, laracroft37 commented on avocado_i2n/vmnet/tunnel.py
> +        in other words they are in directly connected as tunnel peers
Done

2024-09-12 14:40 UTC, laracroft37 commented on avocado_i2n/vmnet/network.py
>          :rtype: (:py:class:`virttest.qemu_vm.VM`, Session object, Params object)
Done

2024-09-12 14:40 UTC, laracroft37 commented on avocado_i2n/vmnet/network.py
>          :param int vm_num: number N of vms
Done

2024-09-12 14:41 UTC, laracroft37 commented on avocado_i2n/vmnet/network.py
> +    def get_ordered_vms(self, vm_num: int = None) -> tuple[VM, VM]:
Done

2024-09-12 14:41 UTC, laracroft37 commented on avocado_i2n/vmnet/network.py
>          :rtype: named tuple
All done

2024-09-12 14:41 UTC, laracroft37 commented on avocado_i2n/vmnet/network.py
> +        Build bridges and interfaces needed to create and isolate the network.
Done

2024-09-12 14:42 UTC, laracroft37 commented on avocado_i2n/vmnet/network.py
> +        vms: VM,
Done

2024-09-12 14:43 UTC, laracroft37 commented on avocado_i2n/vmnet/network.py
> +        Given using heuristics about the tunnels and netconfigs of the entire vm network.
Done

2024-09-12 14:43 UTC, laracroft37 commented on avocado_i2n/vmnet/network.py
> +        Given using heuristics about the tunnels and netconfigs of the entire vm network.
Done

2024-09-12 14:43 UTC, laracroft37 commented on avocado_i2n/vmnet/network.py
> +    ) -> Match[str]:
Done

2024-09-12 14:44 UTC, laracroft37 commented on avocado_i2n/vmnet/network.py
> +    ) -> Match[str]:
Done

2024-09-12 14:47 UTC, laracroft37 commented on avocado_i2n/vmnet/netconfig.py
> +    def netmask(self, value: VMInterface = None) -> VMInterface:
Done

2024-09-12 14:47 UTC, laracroft37 commented on avocado_i2n/vmnet/netconfig.py
> +            return None
Done

2024-09-12 14:49 UTC, laracroft37 commented on avocado_i2n/vmnet/netconfig.py
> +    def gateway(self, value: VMInterface = None) -> VMInterface:
Done

2024-09-12 14:50 UTC, laracroft37 commented on avocado_i2n/vmnet/netconfig.py
> +    def host_ip(self, value: VMInterface = None) -> VMInterface:
Done

2024-09-12 14:51 UTC, laracroft37 commented on avocado_i2n/vmnet/netconfig.py
> +    def range(self, value: VMInterface = None) -> VMInterface:
will wait for your confirmation

2024-09-12 14:52 UTC, laracroft37 commented on avocado_i2n/vmnet/netconfig.py
> +            return None
All done

2024-09-12 14:52 UTC, laracroft37 commented on avocado_i2n/vmnet/netconfig.py
> +        Performing the necessary registrations and finishing
Done

2024-09-12 14:53 UTC, laracroft37 commented on avocado_i2n/vmnet/netconfig.py
> +        Checking this through both IP and actual attachment (to counter same IP range netconfigs).
Done

2024-09-12 14:54 UTC, laracroft37 commented on avocado_i2n/vmnet/netconfig.py
> +        Throw Exceptions if it is already present or the netmask does not coincide (misconfiguration errors).
Done

2024-09-12 14:56 UTC, laracroft37 commented on avocado_i2n/vmnet/netconfig.py
> -        :param interface: interface to translate
Done

2024-09-12 14:58 UTC, laracroft37 commented on avocado_i2n/intertest_setup.py
> -performed only on those machines and not on all. Example is 'vms = vm1 vm2 vm3\n'
Done

2024-09-12 14:59 UTC, laracroft37 commented on avocado_i2n/intertest_setup.py
> +def new_job(config: Params) -> Generator[Job, None, None]:
Done

2024-09-12 14:59 UTC, laracroft37 commented on avocado_i2n/intertest_setup.py
> +    def wrapper(config: Params, tag: str = "") -> Any:
Done

2024-09-12 15:05 UTC, laracroft37 commented on avocado_i2n/states/setup.py
> +    env: ENV,
Done

2024-09-12 15:07 UTC, laracroft37 commented on avocado_i2n/states/setup.py
> +def show_states(run_params: dict[str, str], env: ENV = None) -> list[str]:
Done

2024-09-12 15:08 UTC, laracroft37 commented on avocado_i2n/states/setup.py
>      :returns: list of detected states
Done

2024-09-12 15:08 UTC, laracroft37 commented on avocado_i2n/states/pool.py
> +    def get_sources(cls, do: str, params: Params) -> list["TestObject"]:
Done

2024-09-12 15:14 UTC, laracroft37 commented on avocado_i2n/cartgraph/node.py
> +        """Construct a PrefixTree Node(test) for any test objects (vms)."""
Done

2024-09-12 15:15 UTC, laracroft37 commented on avocado_i2n/cartgraph/node.py
> +    """A node of a prefix tree."""
Done

2024-09-12 15:15 UTC, laracroft37 commented on avocado_i2n/cartgraph/node.py
> +        """Construct a Prefix Tree (test) for any test objects (vms)."""
Done

2024-09-12 15:16 UTC, laracroft37 commented on avocado_i2n/cartgraph/node.py
> +        """Trie structure used for faster prefix lookup."""
Done

2024-09-12 15:16 UTC, laracroft37 commented on avocado_i2n/cartgraph/node.py
> +        """Construct an EdgeRegister (test) for any test objects (vms)."""
Done

2024-09-12 15:17 UTC, laracroft37 commented on avocado_i2n/cartgraph/node.py
> +    Such test relevant unclude like parameters, parser, used objects and
Done

2024-09-12 15:17 UTC, laracroft37 commented on avocado_i2n/cartgraph/node.py
> +        Test is currently traversed by at least N (-1 for all) workers of all or some scopes.
Done

2024-09-12 15:18 UTC, laracroft37 commented on avocado_i2n/cartgraph/node.py
> +        Test was ever traversed by at least N (-1 for all) workers of all or some scopes.
Done

2024-09-25 18:41 UTC, pevogam commented on avocado_i2n/cartgraph/graph.py
Can you remind me what was the standard format for the module docstrings? One or two empty lines between headers?

2024-09-25 18:42 UTC, pevogam commented on avocado_i2n/cartgraph/graph.py
> +import virttest
This belongs with the virttest block.

2024-09-25 18:43 UTC, pevogam commented on avocado_i2n/cartgraph/graph.py
> +
There should be no empty line here.

2024-09-25 18:47 UTC, pevogam commented on avocado_i2n/cartgraph/graph.py
> +        worker_name: str = "",
Investigated this and had to suggest some extra fixes (top commit).

2024-09-25 18:48 UTC, pevogam commented on avocado_i2n/cartgraph/graph.py
> +        def get_display_id(node: "TestNode") -> str:
I am still not sure why we need the quotes here.

2024-09-25 19:01 UTC, pevogam commented on avocado_i2n/cartgraph/graph.py
> +    ) -> list[TestObject] | TestObject:
Could we try with this being just `TestObject` (no list)?

2024-09-25 19:06 UTC, pevogam commented on avocado_i2n/cartgraph/graph.py
> +    ) -> tuple[list[TestNode], list[TestNode]]:
My bad, the above is correct

2024-09-25 19:13 UTC, pevogam commented on avocado_i2n/cartgraph/node.py
> +
This empty line is not needed

2024-09-25 20:05 UTC, pevogam requested changes
Some extra comments wrapped as an extra review of the requested changes

2024-09-25 20:05 UTC, pevogam commented on avocado_i2n/cartgraph/node.py
> +        """Construct a PrefixTree Node(test) for any test objects (vms)."""
No, you have removed the working class docstring and put this in the close while I meant it to be a docstring of the __init__ constructor.

2024-09-25 20:05 UTC, pevogam commented on avocado_i2n/cartgraph/node.py
> +        Check if the test is currently traversed by at least N (-1 for all) workers of all or some scopes.
Not "current traversed" but "was ever traversed"

2024-09-26 07:49 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
1 empty line only

2024-09-26 07:55 UTC, laracroft37 commented on avocado_i2n/plugins/auto.py
> -        Take care of command line overwriting, parameter preparation,
what was the previous docstring?

2024-09-26 07:58 UTC, laracroft37 commented on avocado_i2n/params_parser.py
> -        Parsed file representation used in reports of parsing steps.
Done

2024-09-26 08:05 UTC, laracroft37 commented on avocado_i2n/vmnet/tunnel.py
> +        in other words they are in directly connected as tunnel peers
done

2024-09-26 08:23 UTC, laracroft37 commented on avocado_i2n/cartgraph/node.py
> +        """Construct a PrefixTree Node(test) for any test objects (vms)."""
how do i restore it? I cannot do git diff anymore

2024-09-26 08:25 UTC, pevogam commented on avocado_i2n/cartgraph/graph.py
I see two empty lines between sections in some cases but just 1 line in others. Can you double check all modules have the same docstring formatting standard?

2024-09-26 08:26 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +import virttest
Done

2024-09-26 08:27 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +
Done

2024-09-26 08:30 UTC, pevogam commented on avocado_i2n/plugins/auto.py
> -        Take care of command line overwriting, parameter preparation,
Simply inspect the diff of the pull request and you must be able to see it.

2024-09-26 08:32 UTC, pevogam commented on avocado_i2n/cartgraph/node.py
> +        """Construct a PrefixTree Node(test) for any test objects (vms)."""
The previous diff is shown right above.

2024-09-26 08:52 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +        def get_display_id(node: "TestNode") -> str:
done

2024-09-26 08:54 UTC, laracroft37 commented on avocado_i2n/cartgraph/graph.py
> +    ) -> list[TestObject] | TestObject:
Done

2024-09-26 08:56 UTC, laracroft37 commented on avocado_i2n/cartgraph/object.py
> +        If permanent, it can only be created manuallythrough the use of manual setup steps.
Done

2024-09-26 09:25 UTC, laracroft37 commented on avocado_i2n/states/setup.py
> +    run_params: dict[str, str], env: virttest.utils_env.Env = None
Done

2024-09-26 09:29 UTC, laracroft37 commented on avocado_i2n/cartgraph/node.py
> +        Check if the test is currently traversed by at least N (-1 for all) workers of all or some scopes.
Done

2024-09-26 16:46 UTC, pevogam commented on avocado_i2n/cartgraph/graph.py
> +    ) -> TestObject | list[TestObject] | None:
Let's let this fly because mypy is not verifying our assertions here.

2024-09-26 16:46 UTC, pevogam commented on avocado_i2n/cartgraph/graph.py
> +    ) -> TestObject | NetObject:
Let's let this fly because mypy is not verifying our assertions here.

2024-09-26 16:46 UTC, pevogam commented on avocado_i2n/cartgraph/graph.py
> +    ) -> Any | list[TestNode] | None:
Let's let this fly because mypy is not verifying our assertions here.

2024-09-27 19:55 UTC, pevogam approved these changes
Ok, this looks good now and thanks for all the effort here!

2024-09-27 19:56 UTC, merged